<?php

namespace ContainerAswVrae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_MetadataDriver_AnnotationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'vich_uploader.metadata_driver.annotation' shared service.
     *
     * @return \Vich\UploaderBundle\Metadata\Driver\AnnotationDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Metadata/Driver/AnnotationDriver.php';

        return $container->privates['vich_uploader.metadata_driver.annotation'] = new \Vich\UploaderBundle\Metadata\Driver\AnnotationDriver(($container->privates['vich_uploader.metadata.reader'] ?? ($container->privates['vich_uploader.metadata.reader'] = new \Doctrine\Common\Annotations\AnnotationReader())));
    }
}
