<?php

namespace Container8D7KTom;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_MetadataDriver_ChainService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'vich_uploader.metadata_driver.chain' shared service.
     *
     * @return \Metadata\Driver\DriverChain
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/DriverChain.php';

        return $container->privates['vich_uploader.metadata_driver.chain'] = new \Metadata\Driver\DriverChain([0 => ($container->privates['vich_uploader.metadata_driver.xml'] ?? $container->load('getVichUploader_MetadataDriver_XmlService')), 1 => ($container->privates['vich_uploader.metadata_driver.annotation'] ?? $container->load('getVichUploader_MetadataDriver_AnnotationService')), 2 => ($container->privates['vich_uploader.metadata_driver.yaml'] ?? $container->load('getVichUploader_MetadataDriver_YamlService')), 3 => ($container->privates['vich_uploader.metadata_driver.yml'] ?? $container->load('getVichUploader_MetadataDriver_YmlService'))]);
    }
}
